services:
  leffa_api:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "7860:7860"
    environment:
      - DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    restart: always
    volumes:
      # Option A: bind‐mount a host folder:
      - ./models:/app/ckpts

volumes:
  ckpt-data:
    driver: local